### ISSUE TITLE
tinyxml.cpp:380:25: error: ‘atoi’ was not declared in this scope

### ISSUE THREAD

**Issue by l29ah** [seisatsu/noiz2sa-linux#1]
```
make -C tinyxml
make[2]: Entering directory '/home/test/tmp/noiz2sa-linux/src/bulletml/tinyxml'
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O2   tinyxml.cpp -o tinyxml.o
tinyxml.cpp: In member function ‘const string* TiXmlElement::Attribute(const string&, int*) const’:
tinyxml.cpp:380:25: error: ‘atoi’ was not declared in this scope
   *i = atoi( s->c_str() );
                         ^
make[2]: *** [Makefile:109: tinyxml.o] Error 1
```

**Comment by seisatsu** [comment]
Doesn't happen for me, but my version of G++ is probably newer than yours. Try with the newest commit and let me know if anything else happens.

**Comment by l29ah** [comment]
```
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O2   xmltest.cpp -o xmltest.o
xmltest.cpp: In function ‘int main()’:
xmltest.cpp:57:12: error: ‘exit’ was not declared in this scope
    exit( 1 );
            ^
make[2]: *** [Makefile:109: xmltest.o] Error 1
```

**Comment by seisatsu** [comment]
Try again with the newest commit. Since my version of g++ is different I can't test the changes myself, but if we go back and forth like this it should probably be done in a few more iterations.

What version of g++ are you using, by the way?

**Comment by l29ah** [comment]
It builds fine now, thanks. Sad that it won't run from the build directory.
g++ (Gentoo Hardened 5.4.0-r4 p1.8, pie-0.6.5) 5.4.0

**Comment by seisatsu** [comment]
Nice to see it working. I've made another commit that should dump a working symbolic link to the binary in the top level build directory for running in place.

**Comment by l29ah** [comment]
The problem is not the binary location, but the fact it wants its resources from `/usr/share/games`.

**Comment by seisatsu** [comment]
Oh! Of course, I already had it installed on my machine so I didn't notice. That will probably take a little more work.

**Comment by seisatsu** [comment]
That should work now. If not, open a new issue.
